### ISSUE TITLE
Use of Local Cache

### ISSUE THREAD

**Issue by guw** [ngalaiko/bazel-action#23]
Is it possible to persis the local cache between CI workflow executions of this action?

There is a Cache action available. Not sure if that can work or something else is needed. An example would be nice if that can be used.

**Comment by ngalaiko** [comment]
Hi! 

Great question! 
I was thinking of how to support it in a better way and came to the conclusion that the easiest way is to not use this action. 

Looking at this,  https://github.com/ngalaiko/bazel-action/issues/16 and https://github.com/ngalaiko/bazel-action/issues/19, when [bazelisk](https://github.com/bazelbuild/bazelisk) project exists, and there is a default action to run bash command on the host machine one could just use this to replace the whole action with: 

```yaml
name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...
```

This of course can be prettified by moving it to a seaprate subaction, but I don't really see any reason for it. 

I will archive the project as I don't see any need for it anymore and document it my thoughts.
